language: node_js
node_js:
- 6
before_script:
- phantomjs --version
- phantomjs --webdriver=4444 2>&1 >/dev/null &
- find ./build_scripts -type f -exec chmod +x {} \;
script:
- npm run test
after_success:
- npm run submitcov
- env DISQUS_PROD=true npm run build
- npm run deploy:ci
env:
  global:
  - secure: UzeC9pLigUpriLNKkaDVYymbst7ZoaAq8w1KcDctn62C3YVHFoKIyIUwcUp7OyvhpXCc+BRZxaoCH5XDfAAzVGLXr8axuaWys0aMSyWZ+YAf2CVYKb2P+vyN+miO84AVubEh+8V0rUeeW5K1o3sWCxvO00BY6D6/tHpBNT2Tqw9xqwlrzjDQj8UeyMR5IMrkxOwK90qCjFeu2GXnJCYJbTt77s2S5no8s9af+67TuQdDkRYrjbFLhEenZ1lvNc5stkKuq+Dzz3MphVPWRj2FuOGJrS8ET/dyhi6ssD2vAy+SxilJhsJlpEMISlKn20G729ttpfjZgDCu91wxzuRe5HD2SMtjlhVc88/uL2s5LyY4oeXvrrWJOYLVO8FCLfb1/RGM3+VezNXSPvi64G3SShonJGk6PC0gWsu+0na5fdXVwJZQuwwbxdXl8SWKjFPB7GFsbeZ2GmcbmlVsGX+Ny+5A03pVOJN+nllh2bhNzN2KjRQmzLpwAOuLMncfCvTzpSdB8U34q1atQJbbNeNI3syJFxCkKSIPhu+RreBd5e4DMZd7s8Yt+RHbyoAIrKZqiORn8Zzw+sMG+HYNtzqqshRAXS0gHc9xzloU37ibFB6rhQIQB5iPr+lyo1QUvUCRXsJVq/SeIKs+nIrQ1OwUlFevuLEScbkjSP2ZRypbiKU=
  - secure: C3y/2QZ1hmCANNgj5j0nqZwP9fHaqgQHyCqkdWzQM/AsTwv16+FmDjumRZAmL90cPbv/QoNw1FJdctudJ1MgXn0bEczZU5cPd7p9oamVxZ8HxUur0yaWuL/+kTerigEBf7Q8AMx5+2wvRjCEW7lPwYSldE/0cTce6TrZAR//gdWC8HtHm9P5RPRi9rM6tjGwHypU5D4bQiW2LJ6D8VXx0XQihvDPqLn2hUPVis50buFjBkwKqeUnLN8nPPXOUYd0S516JO+D53B/xsD7hxs6ys2lJJFhp+z8ZdmgzQCfK+nQe2dZQWLBa/gCQRWv16C9Io3jXegR/fJzJ+RJ0rkZvHBEa6wF6gLSllnMDec+x6CpyvcfwwbFY3mxZvnkU6DBSLSs2g6CkzxxbJgQeUDE9SBdSwaI7q0XLWNSqRkZwIhs7bTEpBo77uC8Bm1mypSNOdedZxVDnbzRd8P8DtaNj2r5/0YRe4EgB/iqHEoXxQhjXT7RRsWcILiW83UX/wSK37jmsoN2vtdwoDjIPQyzfLBxKfes7k/lyROsNj/G3/F2NawdCe7eneDq27SC9Z9XFWRCpGiqX/Ai1m+XLQf65PIL6EuG84VAKyV92cwyO2YHVA7cX2tMjGPHs5sp4zPd3CLe3G7Gb5N6SPDQ5s0oGlSLOpvcUwv6FZa0iqyuUac=
