language: node_js
node_js:
  - "stable"

before_script:
 - find ./_scripts -type f -exec chmod +x {} \;

script: npm run rebuild

after_success:
 - npm run ci-deploy

env:
  global:
   - secure: UzeC9pLigUpriLNKkaDVYymbst7ZoaAq8w1KcDctn62C3YVHFoKIyIUwcUp7OyvhpXCc+BRZxaoCH5XDfAAzVGLXr8axuaWys0aMSyWZ+YAf2CVYKb2P+vyN+miO84AVubEh+8V0rUeeW5K1o3sWCxvO00BY6D6/tHpBNT2Tqw9xqwlrzjDQj8UeyMR5IMrkxOwK90qCjFeu2GXnJCYJbTt77s2S5no8s9af+67TuQdDkRYrjbFLhEenZ1lvNc5stkKuq+Dzz3MphVPWRj2FuOGJrS8ET/dyhi6ssD2vAy+SxilJhsJlpEMISlKn20G729ttpfjZgDCu91wxzuRe5HD2SMtjlhVc88/uL2s5LyY4oeXvrrWJOYLVO8FCLfb1/RGM3+VezNXSPvi64G3SShonJGk6PC0gWsu+0na5fdXVwJZQuwwbxdXl8SWKjFPB7GFsbeZ2GmcbmlVsGX+Ny+5A03pVOJN+nllh2bhNzN2KjRQmzLpwAOuLMncfCvTzpSdB8U34q1atQJbbNeNI3syJFxCkKSIPhu+RreBd5e4DMZd7s8Yt+RHbyoAIrKZqiORn8Zzw+sMG+HYNtzqqshRAXS0gHc9xzloU37ibFB6rhQIQB5iPr+lyo1QUvUCRXsJVq/SeIKs+nIrQ1OwUlFevuLEScbkjSP2ZRypbiKU=

cache:
  directories:
    - node_modules
