language: node_js
node_js:
- 10
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_9a39496de4c2_key -iv $encrypted_9a39496de4c2_iv
  -in scripts/deploy_key.enc -out scripts/deploy_key -d
- scripts/ci-prepare
jobs:
  include:
  - stage: branch
    if: type = push
    script:
    - npm test
  - stage: pr
    if: type = pull_request
    script:
    - npm test && npm run deploy:beta
  - stage: master
    if: branch = master AND type = push
    script:
    - npm test && npm run deploy
