language: node_js
node_js:
- 10
services:
- docker
env:
  global:
    secure: n8+W2ffA7rUU2y1F1rsjBs2z20XyOYz/QS8NnKVonTmMPExxwdZV4jIFhwxvVQAvwUS5O5N39XW5pMggRBizqlyuA1T3maCN46ce3duajRIqBILDMye03KjXxA6TjVqUglmUReLUvIvCB+gWOGZy/w6/Z7PL2w+NQ+OVX1KeYmpjfuEmX0zXVM7kMP2E5bPa7RdJCg0mEiHHs1ub4eTOhetZYomEI2QebPjImQGWjMaZP7jP80JZrvRsc1SNFqTwIMTZaELfOcuWZOO8pVnBLjqqfGpcunt3rODa+aJ/jmrpoc/Vcf9/iR6XY4XczhdBOp0Dqjjg+iaLDL6Y0X6RzS2DYrQSpfbxavl77T6KT1tMnoURlPNF1RKvrkVBb0j2pJC430Hzr1l+u3M5t1RPUu1Y5lKQoP/nWBLFejMJgaIR2nloHt0p0mHPKvAlXI8Xdn2HeCDDE9G5Kck8zAMCg/pnnDeCZD2085Cog28jQE1GTtNYuN4Xu6/s4nPgFz00Xzobxnt9lFbQPxYV5tK1kSz6ZjSeODQySeWISQCdx5rggnRr5z3KRkR03Gdp88zo9kf+M1hps95wvbis6AX7mvx2gEKnF6Joh2gZJA95vdptk2UTG5PE7BH6TKvzGVRNJA0S9V1qhtW0bZmlLdLw+T8AYgKNYd/sXrE5tnXomBg=
before_install:
- openssl aes-256-cbc -K $encrypted_9a39496de4c2_key -iv $encrypted_9a39496de4c2_iv
  -in scripts/deploy_key.enc -out scripts/deploy_key -d
- scripts/ci-prepare
jobs:
  include:
  - stage: branch
    if: type = push
    script:
    - npm test && npm run submit-cov
  - stage: pr
    if: type = pull_request
    script:
    - npm test && npm run submit-cov && npm run deploy:beta
  - stage: master
    if: branch = master AND type = push
    script:
    - npm test && npm run submit-cov && npm run deploy
