# Hexo Configuration

# Site
title: jonlauridsen.com
author: Jon Lauridsen
language: en

# URL
url: http://jonlauridsen.com/blog
root: /blog/
permalink: :year/:title/

# Writing
new_post_name: :year-:title.md # File name of new posts
titlecase: true
filename_case: 1
post_asset_folder: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: true

# Extensions
theme: apollo
theme_config:
  menu:
      Blog: /blog/
      Archive: /blog/archives/
  favicon:
  logo:
  ga:
  startyear: 2016

archive_generator:
    per_page: 0
    yearly: false
    monthly: false
    daily: false

toc:
  maxdepth: 3
  class: toc
  anchor:
    symbol: '#'

markdown:
  render:
    html: true
