# Hexo Configuration

# Site
title: jonlauridsen.com
author: Jon Lauridsen
language: en

# URL
url: http://jonlauridsen.com
root: /
permalink: blog/:year/:title/
archive_dir: blog

# Writing
new_post_name: :year-:title.md
titlecase: true
filename_case: 1
post_asset_folder: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: true

# Extensions
theme: apollo
theme_config:
  menu:
    Home: /
    Blog: /blog/
  favicon:
  logo:
  ga:
  startyear: 2016

archive_generator:
  per_page: 0
  yearly: false
  monthly: false
  daily: false

toc:
  maxdepth: 3
  class: toc
  anchor:
    symbol: '#'

markdown:
  render:
    html: true # Required for toc
    breaks: false
    linkify: true
    typographer: true
    quotes: '“”‘’'
