#!/bin/bash
set -e # exit with nonzero exit code if anything fails

if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
  echo "Deploying..."
  git config --global user.name "travis-ci"
  git config --global user.email "travis@travis-ci.org"
  npm run deploy
else
  echo "Skipping deploy"
fi
