#!/usr/bin/env node
"use strict";
const sauceConnectLauncher = require("sauce-connect-launcher")

sauceConnectLauncher({
  verbose: true,
  tunnelIdentifier: process.env.TRAVIS_JOB_NUMBER || "development"
}, (err, sauceConnectProcess) => {
  if (err) {
    console.log(err.message)
    return
  }
  console.log("Sauce Connect ready")
})
