#!/bin/bash
set -e # exit with nonzero exit code if anything fails

echo "Generating coverage report"
npm test

if [ "$TRAVIS_REPO_SLUG" == "gaggle/gaggle" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
  echo "Starting continuous deployment script"
  git config --global user.name "travis-ci"
  git config --global user.email "travis@travis-ci.org"
  npm run deploy
else
  echo "Skipping continuous deployment"
fi
