menu:
  Home: /
  Blog: /blog/
  Rss: /atom.xml

ga:

authors:
  gaggle:
    name: Jon Lauridsen
    blurb: Software developer, and automated quality assurance aficionado.
    pic: /img/jon.jpg
    twitter: https://twitter.com/jonlauridsen
    github: https://github.com/gaggle
